#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 1000
      min-spare: 30
    uri-encoding: utf-8

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations:
    - classpath:/mappers.sys/*.xml

#log
logging:
  level:
    '[com.qqls]': debug

#spring
spring:
  datasource:
    url: jdbc:mysql:///yxgsys?serverTimezone=GMT%2B8
    username: root
    password: ROOT
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false